networks:
  pi-net:
    external: true

services:
  les-bons-comptes:
    build: .
    image: les-bons-comptes:latest
    container_name: les-bons-comptes
    restart: unless-stopped
    networks:
      - pi-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.les-bons-comptes.rule=Host(`les-bons-comptes.valodin.fr`)"
      - "traefik.http.routers.les-bons-comptes.entrypoints=web"
      - "traefik.http.services.les-bons-comptes.loadbalancer.server.port=80"
